package io.github.c1921.pillring.permission

enum class PermissionAction {
    OPEN_NOTIFICATION_SETTINGS,
    OPEN_EXACT_ALARM_SETTINGS,
    OPEN_BATTERY_OPTIMIZATION_SETTINGS,
    OPEN_APP_DETAILS_SETTINGS,
    OPEN_XIAOMI_AUTOSTART_SETTINGS
}
